CREATE TYPE game_status_enum AS ENUM ('WAITING', 'ACTIVE', 'COMPLETED', 'CANCELLED');
CREATE TYPE game_type_enum AS ENUM ('SINGLEPLAYER', 'MULTIPLAYER');
CREATE TYPE cell_type_enum AS ENUM ('SHIP', 'SEA', 'MISS', 'HIT');